# Generated by Django 5.2 on 2025-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='img_url',
            field=models.CharField(default='empty', max_length=2000),
        ),
    ]
