# Generated by Django 5.2 on 2026-01-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuitem_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='img_url',
            field=models.CharField(default='static/Images/', max_length=200),
        ),
    ]
