# Generated by Django 5.2 on 2025-12-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
