# Generated by Django 5.2 on 2026-01-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_updated_at',
        ),
    ]
