# Generated by Django 5.2 on 2026-02-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='null', max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
