# Generated by Django 5.2 on 2026-02-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
